version: 0.2

env:
  variables:
    SOLUTION: .\PayPalExercise.sln
    DOTNET_FRAMEWORK: 4.6.2

phases:
  build:
    commands:
      -  nuget restore
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" -p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v$env:DOTNET_FRAMEWORK" $env:SOLUTION'
artifacts:
  files:
    - .\PayPalExercise\bin\Debug\*
