version: 0.2

env:
  variables:
    PROJECT: PayPalExercise
    DOTNET_FRAMEWORK: 4.5.2
phases:
  build:
    commands:
      - nuget restore
      - msbuild $env:PROJECT.csproj /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK 
artifacts:
  files:
    - '**/*'
